# Build output will be a CosmosDB resource created via Terraform
# Branches will only validate, test, format, init, plan

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy

variables:
  - name: timeoutInMinutes
    value: 60
  - name: action
    value: ${{ parameters.action }}
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

steps:
  - script: |
      echo "My working directory is $(working-dir)"