# Build output will be a container image pushed to ARC on merged to master
# Branches will only test code, install necessary libraries etc

parameters:
  prImage: ""
  workingDirectory: ""

steps:
  - script: |
      echo "Helm Chart Reports"